### PR TITLE
added support for animated background

### PR DESCRIPTION
**Pull request by schnusch**
* `FakeCam.images["background"]` is now a looping iterator of background images
  * first try `cv2.imread` background image, otherwise use `cv2.VideoCapture`

### CODE REVIEW

**Comment by fangfufu** [comment]
Thanks! :)

**Comment by fangfufu** [comment]
Ok, I updated readme, thank you so much! Do you have a funny background that you would recommend?

**Comment by schnusch** [comment]
I'm unsure because of licensing and I also wouldn't commit a large video file to the repo, nevertheless "Never Gonna Give You Up" comes to mind.

Am 19. Mai 2020 17:34:37 MESZ schrieb Fufu Fang <notifications@github.com>:

**Comment by fangfufu** [comment]
It is okay, I wasn't suggesting you to commit a large video file. The default background shipped with this repository is in public domain - it is from the White House. 

Anyways, do you literally download the whole video and specify it? Would it loop once the video finishes playing?

**Comment by fangfufu** [comment]
Okay, if anyone else is reading this, this website has a lot of good backgrounds: 
https://coverr.co/tags/zoom-virtual-backgrounds

**Comment by schnusch** [comment]
I made a mistake renaming a variable, so an error occurs, when the background video needs to be looped.

[commit 91d8b73](https://github.com/schnusch/Linux-Fake-Background-Webcam/commit/91d8b73)
```
fixed error on looping of animated background
  * rewind VideoCapture, not generator
```

```diff
diff --git a/fakecam/fake.py b/fakecam/fake.py
index 57ee755..9809f87 100644
--- a/fakecam/fake.py
+++ b/fakecam/fake.py
@@ -96,7 +96,7 @@ class FakeCam:
                         ret, frame = background_video.read()
                         if not ret:
                             background_video.set(cv2.CAP_PROP_POS_FRAMES, 0)
-                            ret, frame = background.read()
+                            ret, frame = background_video.read()
                             assert ret, 'cannot read frame %r' % self.background_image
                         frame = cv2.resize(frame, (self.width, self.height))
                         yield frame
```

**Comment by fangfufu** [comment]
@schnusch , yeh, I saw the mistake and fixed it for you. :)

**Comment by schnusch** [comment]
yeah, I noticed, but just *after* commmenting...

**Pull request merged**
