### PR TITLE
re-add hologram, optionally

### PR DESCRIPTION
**Pull request by rwthompsonii**

### CODE REVIEW

**Comment by fangfufu** [comment]
Thanks, would you like to write a bit of documentation?

**Comment by rwthompsonii** [comment]
Um, sure, just not sure what it needs. I just added the existing hologram
code into it.

**Comment by fangfufu** [comment]
I meant explaining your hologram stuff in ``README.md``.

**Comment by rwthompsonii** [comment]
Ah, yes I'll add that.

**Pull request merged**
