### PR TITLE
Add config file support

### PR DESCRIPTION
**Pull request by rcelha**
Using the ConfigArgParse library we have option parity between args and
config files (ini format)

solves #145

### CODE REVIEW

**Comment by rcelha** [comment]
Firstly I implemented this only with the standard library, but as I went I realized I was just reimplementing https://pypi.org/project/ConfigArgParse. So I decided to scrap it and just use the library.

Let me know what you think, and in the mean time I will run some more tests on it.

Cheers

**Comment by fangfufu** [comment]
I tested it, I quite like it. I have no problem with merging it as it is. Let me know if you want me to merge it. :slightly_smiling_face:

**Comment by rcelha** [comment]
Hey @fangfufu  I did some more tests this morning and I am happy merging it now. 

BTW, I forgot to say, but this is a such nice project and I've been using it for the past few weeks daily!

**Comment by fangfufu** [comment]
Thanks, merged! :)

**Pull request merged**
