### PR TITLE
make small images tiled.

### PR DESCRIPTION
**Pull request by watayan**
Hello
This patch makes tile a small background images.

### CODE REVIEW

**Comment by fangfufu** [comment]
I am not sure if people expect this kind of behaviour. Could you add a flag to switch it on and off?

**Comment by fangfufu** [comment]
I will merge the patch for now.

**Comment by fangfufu** [comment]
ok, I changed the behaviour in 00c46c5a3fa7dd3b93e4ecae361471bb01c1c0a0, it is now enabled when you use the ``--tile-background`` flag.

**Comment by watayan** [comment]
Thank you.

**Pull request merged**
