### PR TITLE
Enabled to change extension of foreground/background images.

### PR DESCRIPTION
**Pull request by watayan**
Hello.
When I copied  background.jpeg to fakecam folder and removed background.jpg, fake.py died with Ctrl+C. So I wrote a patch for this problem.

### CODE REVIEW

**Comment by fangfufu** [comment]
Cool thanks!

**Comment by watayan** [comment]
Thank you!

**Comment by fangfufu** [comment]
Hi, I reverted this change, because of https://github.com/fangfufu/Linux-Fake-Background-Webcam/issues/157. To be honest, my intention had never been allowing the user to change the filename of the background picture on the fly.

**Comment by watayan** [comment]
All right, I understand.

**Comment by watayan** [comment]
In this fake.py, default value of "-b" is "background.*", but I think the wildcard won't work.

**Comment by fangfufu** [comment]
Ah yes, thanks for pointing that out. I just removed the wildcards from the defaults. I am not sure when they were added in, but I don't think that's my original intention. The original intention has always been specifying the file, rather than allowing wildcard.

**Pull request merged**
